### PR TITLE
update policy definitions with ec2:CopyImage and ec2:CreateTags

### PR DESCRIPTION
**Pull request by infinitewarp**

### CODE REVIEW

**Comment by infinitewarp** [comment]
It looks like my editor automatically stripped off the trailing whitespace from a few unrelated lines upon save. If this is a problem, please let me know and I will manually add them back.

**Review by cdcabrera — COMMENTED** [review]
@infinitewarp the spacing issue happened to @abaiken too. the `snapshot` files are autogenerated. Looks like I need to go back and update how those files are handled. It's up to you whether you want to remove it since it may happen to another developer. My preference is remove it, let the PR focus on what it's aimed at. If you decide to roll with it, give me a heads up.

In the meantime I'll go ahead and look at the unit testing framework config

**Review by cdcabrera — APPROVED** [review]

**Comment by infinitewarp** [comment]
Ahhhh, OK. I didn't realize the snap files were generated. Maybe they should be .`gitignore`d?

Since the snap file is generated but checked in to the repo, I'll leave this change as-is since the net effect _should_ be the same.

**Comment by cdcabrera** [comment]
Some quick testing, now I remember. @infinitewarp so it appears the spacing is needed within the snapshots. Looks like in order for the HTML snapshots to compare what template/component/view "was" vs "what is now" the comparison makes use of everything. 

Easy fix on my part, have to re-check the snapshot in since the configuration.json file was updated. I'll continue looking at the config, maybe there's a way to stipulate that editors should ignore those files through the `.editorconfig`

**Pull request merged**
